# Generated by Django 4.2 on 2023-04-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electrolyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electrolyzer_number', models.IntegerField()),
                ('release_date', models.DateField()),
                ('shutdown_date', models.DateField()),
                ('shutdown_life', models.FloatField()),
                ('average_lifetime', models.FloatField()),
            ],
        ),
    ]
