# Generated by Django 4.2 on 2023-05-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrolyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrolyzer',
            name='days_up',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='failure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
