# Generated by Django 4.2 on 2023-06-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrolyzer', '0002_alter_electrolyzer_days_up_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateField()),
                ('failure_date', models.DateField(blank=True, null=True)),
                ('days_up', models.IntegerField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
