# Generated by Django 4.2 on 2023-06-26 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electrolyzer', '0004_location_parttype_remove_history_days_up_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrolyzer.part'),
        ),
    ]
