# Generated by Django 4.2 on 2023-06-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrolyzer', '0005_alter_history_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='avg_working_months',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='months_up',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
