# Generated by Django 4.2 on 2023-06-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrolyzer', '0006_part_avg_working_months_alter_history_months_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='months_up',
            new_name='months',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='avg_working_months',
            new_name='avg_months',
        ),
    ]
