# Generated by Django 4.2 on 2023-06-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrolyzer', '0007_rename_months_up_history_months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='months',
        ),
        migrations.RemoveField(
            model_name='part',
            name='avg_months',
        ),
        migrations.AddField(
            model_name='history',
            name='days',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='avg_days',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
