# Generated by Django 4.2 on 2023-06-27 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electrolyzer', '0008_remove_history_months_remove_part_avg_months_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='part',
            name='location',
        ),
        migrations.AlterField(
            model_name='history',
            name='failure_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата поломки'),
        ),
        migrations.AlterField(
            model_name='history',
            name='launch_date',
            field=models.DateField(verbose_name='дата запуска'),
        ),
        migrations.AlterField(
            model_name='part',
            name='avg_days',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrolyzer.factory')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='electrolyzer.factory'),
        ),
        migrations.AlterField(
            model_name='electrolyzer',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrolyzer.building'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
