# Generated by Django 4.2 on 2023-06-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electrolyzer', '0009_factory_remove_part_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrolyzer.factory'),
        ),
    ]
