# Generated by Django 4.2 on 2023-06-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electrolyzer', '0010_alter_part_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrolyzer.factory', unique=True),
        ),
    ]
