# Generated by Django 4.2 on 2023-06-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electrolyzer', '0011_alter_building_factory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='factory',
        ),
        migrations.AddField(
            model_name='part',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='electrolyzer.building'),
        ),
    ]
