# Generated by Django 4.2 on 2023-06-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electrolyzer', '0012_remove_part_factory_part_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrolyzer.building'),
        ),
    ]
