# Generated by Django 4.2 on 2023-06-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electrolyzer', '0013_alter_part_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='factory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='electrolyzer.factory'),
        ),
    ]
