# Generated by Django 4.2 on 2023-06-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrolyzer', '0017_alter_building_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='number',
            field=models.IntegerField(verbose_name='номер'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('number', 'part_type', 'building')},
        ),
    ]
